### ISSUE TITLE
missing import file

### ISSUE THREAD

**Issue by MnlPhlp** [ThomasTJdev/nimwc_openregistration#1]
the extension throws an error when trying to import utils/random_generator, because the file does not exist anymore in nimWC.

**Comment by ThomasTJdev** [comment]
Thanks. That's a regression from refractor of NimWC. I'll update it soon, unless you'll push a PR.

**Comment by MnlPhlp** [comment]
I got it working locally using [sysrandom](https://github.com/euantorano/sysrandom.nim) and its getRandomString.
I don't want to add this as a PR because of the additional dependencie.
How should this be fixed? Write a random string function here or add one to nimWC? I could do a PR I'm just not sure what's the best way to fix this.

**Comment by ThomasTJdev** [comment]
Hi @manniq31 

A PR would be really nice!

I would vote for a proc in `nimwc_openregistrations`-repo or a reuse of existing code in NimWC. We [removed the random generator](https://github.com/ThomasTJdev/nim_websitecreator/search?q=Clean+out+code%2C+simplify+the+starting+random+password&unscoped_q=Clean+out+code%2C+simplify+the+starting+random+password&type=Commits) from NimWC core, to keep the core code slim.

Currently in the NimWC core we use a custom rand-generator for 2fa and normal rand for passwords (for inspiration):
https://github.com/ThomasTJdev/nim_websitecreator/blob/96bafe77a862922da5a8f6ce19ff1e44e901531a/nimwcpkg/tmpl/user.tmpl#L307-L311
https://github.com/ThomasTJdev/nim_websitecreator/blob/96bafe77a862922da5a8f6ce19ff1e44e901531a/nimwcpkg/resources/web/routes.nim#L749-L753
